version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=travel_diary_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/travel_diary_db
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db-data: